#:schema node_modules/wrangler/config-schema.json
name = "shamo-newweb"
compatibility_date = "2025-04-01"
assets = { directory = "./dist/", not_found_handling = "single-page-application" }
services = [
  { binding = "API", service = "shamo-api" }
]
workers_dev = false
routes = [
  { pattern = "shamonew.mi-wada.com", custom_domain = true }
]
[vars]
SHAMO_API_BASE_URL = "https://shamo-api.mi-wada.com"
# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
